---
wp_cli_src: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
wp_cli_bin: /usr/local/bin/wp
wp_root_loc: /var/www/html
wp_root_dbuser: root
wp_root_dbpass: MySQLServer@123
wp_adminuser: admin
wp_adminpass: MySQLServer@123
wp_adminmail: info@devopsthink.com
wp_url: localhost.com
wp_title: Wordpress Title
wp_dbname: devopsdb
wp_dbuser: devopsuser
wp_dbpass: MySQLServer@123
wp_dbhost: localhost
wp_locale: en_US